name: Sync Branches

on:
  push:
    branches: [main]
    repository: pawelrogowski/soYum-backend

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: pawelrogowski/soYum-backend
          token: ${{ secrets.SECOND_REPO_GITHUB_TOKEN }}

      - name: Remove cloned repo
        run: |
          rm -rf soyum-backend-remote

      - name: Clone repository
        run: |
          git clone https://${{ secrets.SECOND_REPO_GITHUB_TOKEN }}@github.com/orimorfus/soyum-backend-remote.git

      - name: Force push to sync-test
        run: |
          git push origin --force HEAD:sync-test
