name: Sync Branches

on:
  push:
    branches: [main]
    repository: pawelrogowski/soYum-backend

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: pawelrogowski/soYum-backend
          token: ${{ secrets.SECOND_REPO_GITHUB_TOKEN }}

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Force push main branch
        run: |
          git push --force https://orimorfus:${{ secrets.SECOND_REPO_GITHUB_TOKEN }}@github.com/orimorfus/soyum-backend-remote.git HEAD:main
