name: Sync Branches

on:
  push:
    branches: [main]
    repository: pawelrogowski/soYum-backend

env:
  GH_TOKEN: ${{ secrets.SECOND_REPO_GITHUB_TOKEN }}

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: pawelrogowski/soYum-backend
          token: ${{ secrets.SECOND_REPO_GITHUB_TOKEN }}

      - name: Remove cloned repo
        run: |
          rm -rf soyum-backend-remote

      - name: Clone repository
        run: |
          gh repo clone orimorfus/soyum-backend-remote

      - name: Force push to sync-test
        run: |
          gh repo push orimorfus/soyum-backend-remote --force --branch sync-test
