name: Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: orimorfus/soyum-backend-remote
          ref: main

      - name: Setup Git
        run: |
          git config --global user.name "Feiron"
          git config --global user.email "pawel.rogowski.praca@gmail.com"

      - name: Add remote
        run: |
          git remote add sync-repo https://${{ secrets.SYNC_REPO_TOKEN }}@github.com/orimorfus/soyum-backend-remote.git

      - name: Push changes
        run: |
          git push sync-repo main
